name: rccar
description: "rccar"

version: 1.0.0+1

environment:
  sdk: "^3.7.2"

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.8
  flutter_webrtc: ^0.13.1+hotfix.1
  web_socket_channel: ^3.0.3
  shared_preferences: ^2.2.0
  http: ^0.13.3
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  device_info_plus: ^10.0.0
  mqtt_client: ^10.8.0
  flutter_joystick: ^0.2.2
#  gamepads: ^0.1.7
  sdl_gamepad: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

